apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: docker.io/paraso1ka/flask-app:4f33a7d61ff0bb1481b90308c5cb9862202ae737
          ports:
            - containerPort: 5000
